### PR TITLE
Upgrade graphql-java version to 13.0 

### PR DESCRIPTION
**Pull request by igdianov**
This PR is a fork from https://github.com/introproventures/graphql-jpa-query/pull/205 that adds  the following changes to original commit:

* refactor: added DataFetchingEnvironmentBuilder wrapper class …
* refactor(JavaScalars): Renamed method toScalarType to newScalarType
* fix: Resolved NPE with nullable arguments in GraphQLJpaExecutor.execute
* polish: Replaced NullValue builder() with `NullValue.Null`instance
* refactor: Removed ExecutionResult implementation from GraphQLJpaQueryStarterIT
* feat: added support to merge CodeRegistries
* feat: added test example for graphql-java-annotations library

### CODE REVIEW

**Comment by molexx** [comment]
Thanks, this is mostly working for me.

I'm having problems when merging with the schema generated by [graphql-java-annotations](https://github.com/Enigmatis/graphql-java-annotations/) though. It looks like the schema merging code in `GraphQLSchemaFactoryBean.java` doesn't account for CodeRegistries, do you think it ought to?

I've confirmed that it works ok if I declare its GraphQLSchema as the primary Spring bean and so disabling the rest of the autoconfiguring and merging.

Thanks

**Comment by igdianov** [comment]
@molexx Thanks! I will add support for code registry merge to enable merging different schemas via factory bean. Stay tuned...

**Comment by negesti** [comment]
@igdianov as you mentioned in #205 adding the CodeRegistry to the SchemaFactory Bean would require changes in v0.3 not only v.0.4

One option would be, to add an additional GraphQLSchemaFactoryBean that extends the default one and adds support for the CodeRegistry. Imho this would only require some minor changes in the existing FactoryBean (mostly changing private to protected) and makes "back-porting" changes from 0.4 to 0.3 easier. 
Adding an empty function like "mergeAdditionalSchemaData" would be great for #163 to. Or maybe a flexible way to add SchemaMergers that get both schemas and can merge/copy definitions

**Comment by igdianov** [comment]
@negesti @molexx Please, see the proposed support for handling merge of code registries in this commit: https://github.com/introproventures/graphql-jpa-query/pull/209/commits/77e849730c6e8e0b71a01316d6f29fc95d61cacc

It should make it possible to transparently 

In my opinion, the code registry is very bad feature that makes field to code bindings with static coordinates(parent, name) instead of object tree. There is no validation of any kind in GraphQL if you make a mistake in coordinate name and add binding to non-existing field. May be we should have it?

**Comment by igdianov** [comment]
@molexx I have added example tests for `graphql-java-annotations` library: https://github.com/introproventures/graphql-jpa-query/pull/209/commits/744dddfb2117063644a0ffec9581475c66e697c5

Feel free to add any other test case that you may want to cover with code registry

**Comment by molexx** [comment]
Yes this works for me now, thanks! :-)

**Comment by molexx** [comment]
RE validation, yes it would be good I think. There is validation elsewhere - non matching or duplicate types for instance - so it would be consistent.

This functionality is creeping away from JPA. I wonder if it might make sense to split this out into a separate stitching library for graphql-java - and optionally Spring - that graphql-jpa-query-autoconfigure can depend on?

**Pull request merged**
