### PR TITLE
Add support for IN/NIN, BETWEEN/NOT_BETWEEN predicates for floating point numbers

### PR DESCRIPTION
**Pull request by rtmkv**
- Add array value predicate handling for floating point numbers in JpaPredicateBuilder
- Add test entity FloatingThing
- Add test cases to GraphQLExecutorTests

### CODE REVIEW

**Comment by proth1** [comment]
> * Add array value predicate handling for floating point numbers in JpaPredicateBuilder
> * Add test entity FloathingThing
> * Add test cases to GraphQLExecutorTests

Hi @rtmkv I think you may have a typo in your comment / 2nd bullet where "FloathingThing" should be "FloatingThing"

**Comment by vporoxnenko** [comment]
@proth1 @czyba @molexx @negesti 
guys, pls review somebody this pr I also want this feature

**Comment by bahurski-ivan** [comment]
@igdianov sorry for direct tag, but is there any change to get this merged?

**Comment by igdianov** [comment]
@bahurski-ivan, @rtmkv, @vporoxnenko  Thank you for contribution. I can also backport it into `0.4.x` maintenance branch.

**Pull request merged**
