### PR TITLE
#102 fix NullPointerException when searching for Transient annotation

### PR DESCRIPTION
**Pull request by chanhengseang3**
fix Issues #102 

When ever the `Entity` has methods that is `public` and have method name starting with `set` , building schema will fail. This version make a small change ( bypass check for read properties  ) so that build can pass.  
```
@Data
@Entity
public class Book {
	@Id
	Long id;

	@GraphQLIgnoreOrder
	@GraphQLIgnoreFilter
	String title;

	@ManyToOne(fetch=FetchType.LAZY)
	Author author;

	@Enumerated(EnumType.STRING)
	Genre genre;

	/**
	 * Method that have name start with "set" and have at least one arguments will Lead to Error on build time
	 * *Method* that doesn't have a argument won't give error
         * *Method* that does not public won't give error
	 * @param i
	 */
	public void setSth(int i){
		return;
	}

}
```

### CODE REVIEW

**Comment by chanhengseang3** [comment]
I added a method in Entity `Book.java`. I think there is no need to write another test case , because failure happen during build schema, all the other test will fail automatically when try to build schema if the bug is not fixed.

**Comment by igdianov** [comment]
@chanhengseang3 Please use https://github.com/introproventures/graphql-jpa-query/blob/master/graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/calculated/CalculatedEntity.java test model to make the changes to entity model. 

Then use https://github.com/introproventures/graphql-jpa-query/blob/master/graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/CalculatedEntityTests.java to run tests. 

Also, add another test to https://github.com/introproventures/graphql-jpa-query/blob/master/graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/impl/IntrospectionUtilsTest.java to make sure that IntrospectionUtils can handle this case.

**Comment by chanhengseang3** [comment]
I made change of test. 

- Added a set method in https://github.com/introproventures/graphql-jpa-query/blob/master/graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/calculated/CalculatedEntity.java

- Added a test in https://github.com/introproventures/graphql-jpa-query/blob/master/graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/impl/IntrospectionUtilsTest.java to test if IntrospectionUtilsTest can handle the case.

- Another test in https://github.com/introproventures/graphql-jpa-query/blob/master/graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsSchemaBuildTest.java to test if schema build is successful.

**Comment by igdianov** [comment]
@chanhengseang3 LGTM! I am merging this into master branch. Thank you very much for your contribution!

**Pull request merged**
