### PR TITLE
feat: add where relation attributes criteria expressions

### PR DESCRIPTION
**Pull request by igdianov**
fixes https://github.com/introproventures/graphql-jpa-query/issues/76

This PR adds support for many-to-one and one-to-many entity attributes in where criteria expressions with variable parameter bindings, i.e.

Given the following query with many-to-one relation:

```
query($authorId: Long) {  
  Books(where: {
    author: {id: {EQ: $authorId}}
  }) {
    select {
      id
      title
      genre
      author {
        id
        name
      }
    }
  }
}
variables:  { "authorId": 1 }
```

will result in

```
{
  "data": {
    "Books": {
      "select": [
        {
          "id": 2,
          "title": "War and Peace",
          "genre": "NOVEL",
          "author": {
            "id": 1,
            "name": "Leo Tolstoy"
          }
        },
        {
          "id": 3,
          "title": "Anna Karenina",
          "genre": "NOVEL",
          "author": {
            "id": 1,
            "name": "Leo Tolstoy"
          }
        }
      ]
    }
  }
}
```

And given the following query with one-to-many relation:

```
query {
  Authors(where: {
    books: {genre: {IN: NOVEL}}
  }) {
    select {
      id
      name
      books {
        id
        title
        genre
      }
    }
  }
}
```

will result in 

```
{
  "data": {
    "Authors": {
      "select": [
        {
          "id": 1,
          "name": "Leo Tolstoy",
          "books": [
            {
              "id": 2,
              "title": "War and Peace",
              "genre": "NOVEL"
            },
            {
              "id": 3,
              "title": "Anna Karenina",
              "genre": "NOVEL"
            }
          ]
        }
      ]
    }
  }
}
```

It is possible to use compound criterias in where search expressions given:

```
query {
  Authors(where: {
    books: {
      genre: {IN: NOVEL}
      title: {LIKE: "War"}
    }
  }) {
    select {
      id
      name
      books {
        id
        title
        genre
      }
    }
  }
}
```

Will return filtered inner collection result: 

```
{
  "data": {
    "Authors": {
      "select": [
        {
          "id": 1,
          "name": "Leo Tolstoy",
          "books": [
            {
              "id": 2,
              "title": "War and Peace",
              "genre": "NOVEL"
            }
          ]
        }
      ]
    }
  }
}
```

It is also possible to filter inner collections as follows:

```
query {
  Authors(where: {
    books: {genre: {IN: NOVEL}}
  }) {
    select {
      id
      name
      books(where: {title: {LIKE: "War"}}) {
        id
        title
        genre
      }
    }
  }
}
```

will result in 

```
{
  "data": {
    "Authors": {
      "select": [
        {
          "id": 1,
          "name": "Leo Tolstoy",
          "books": [
            {
              "id": 2,
              "title": "War and Peace",
              "genre": "NOVEL"
            }
          ]
        }
      ]
    }
  }
}
```

### CODE REVIEW

**Comment by igdianov** [comment]
@molexx I think it is good to be merged with the last fix. Have you tried it? Let me know.

**Comment by molexx** [comment]
Thanks. Will be tested from our front-end project tomorrow, I'll let you know!

**Comment by molexx** [comment]
Thanks, this works but is a bit restricted in that you can only use a relationship of the first entity, after that you can only use simple attributes as before.

For example:
```
query {  
  Books(where: {
    author: {id: {EQ: 1}}
  }) {
    select {
      id
      title
      genre
      author {
        id
        name
      }
    }
  }
}
```
you can say '`author: {id: `' but you can't say '`author: {books: `'.
Would it be possible to allow this please?

**Comment by igdianov** [comment]
@molexx This is not possible right now. I had to disable nested relationship attributes is search criteria expressions because it is not clear right now how to construct complex joins and predicates for Jpa queries to make it work correctly. If you have any ideas let me know. 

I am also working on optimizing predicate building to avoid duplicating predicates in SQL where expressions. There is a strange caching issue that makes Hibernate cache first result for filtered collection. After that, it will keep returning the same result even if collection filter changes. I experience this via GraphiQL app only, but the unit tests work as expected..

**Comment by igdianov** [comment]
@molexx I am ready to merge this PR if there are no other comments. We can try to solve complex relation attribute criteria expressions later. I just want to be careful about it.

I have also resolved Hibernate object mapping caching issue by clearing session cache with `entityManager.clear()` before every query. Nothing else worked for me. It looks like a bug in Hibernate.

**Comment by molexx** [comment]
Continuing the conversation about nesting relationships in #97

**Pull request merged**
