### PR TITLE
fix: support uppercase attribute names introspection

### PR DESCRIPTION
**Pull request by igdianov**
Fixes https://github.com/introproventures/graphql-jpa-query/issues/172 https://github.com/introproventures/graphql-jpa-query/issues/174

### CODE REVIEW

**Comment by igdianov** [comment]
@pierrefoyard Please, check the fix. Feel free to add your unit tests..

**Comment by igdianov** [comment]
@anotender @SinaiNIN I had refactored `IntrospectionUtils`  to use `ManagedType` to be able to resolve annotations for transient and persistent properties and getter methods within class hierarchy. 

Give it a spin and let me know if there are any problems.

**Comment by anotender** [comment]
@igdianov I've checked new changes against the model in our app but the issue with protected getter and field present in the metamodel still unfortunately exist. We use `org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor` do generate the metamodel and it generates attribute from the protected getter while the `Introspector.getBeanInfo(...)` finds only public ones. It'll be greate if we can include non-public fields into introspection.

**Comment by igdianov** [comment]
@anotender I have added introspection support for protected getter methods (d88953c8b892294007bd75792f6872f80d0f7739). Let me know if it works for you.

**Comment by anotender** [comment]
@igdianov I checked with our entity model and it looks like it works as it should for us. You're right about the test coverage of the code introduced so we need to add tests for it in the near future.

**Pull request merged**
