### PR TITLE
EmbeddedId management

### PR DESCRIPTION
**Pull request by ludovicmotte**
Hi,
This is a new feature : managing JPA @EmbeddedId
Best regards.

### CODE REVIEW

**Comment by igdianov** [comment]
@ludovicmotte Thank you very much for your PR! I really dig the feature to enable support for `@EmbeddableId`, but implementation only works for single entity queries. 

I would expect the following plural entity query to be resolved as follows:

```
    @Test
    public void queryForEntitiesWithEmeddableTypeAndWhereEmbeddableId() {
        //given
        String query = "{ Boats(where: {boatId: {EQ: {id: \"1\" country: \"EN\"}}}) { select { boatId {id country} engine { identification } } } }";

        String expected = "{Boats={select=[{boatId={id=1, country=EN}, engine={identification=12345}}]}}";

        //when
        Object result = executor.execute(query).getData();

        // then
        assertThat(result.toString()).isEqualTo(expected);
    }
```

This test fails with the following exception:

```
java.lang.IllegalArgumentException: Unsupported field type class com.introproventures.graphql.jpa.query.schema.model.embedded.Boat$BoatId for field boatId
	at com.introproventures.graphql.jpa.query.schema.impl.JpaPredicateBuilder.getTypedPredicate(JpaPredicateBuilder.java:370) ~[classes/:na]
	at com.introproventures.graphql.jpa.query.schema.impl.JpaPredicateBuilder.getPredicate(JpaPredicateBuilder.java:384) ~[classes/:na]
	at com.introproventures.graphql.jpa.query.schema.impl.QraphQLJpaBaseDataFetcher.lambda$25(QraphQLJpaBaseDataFetcher.java:397) ~[classes/:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
```

**Comment by ludovicmotte** [comment]
@igdianov Thanks for the review, I understand your point.
I think that for multiple entity queries you could consider EmbeddedId as Embedded (both are Embeddable):

```
    @Test
    public void queryForEntitiesWithWithEmbeddedIdWithWhere() {
        //given
        String query = "{ Boats { select { boatId(where: { AND: {id: { LIKE: \"1\"} country: { EQ: \"EN\"}}}) {id country} engine { identification } } } }";

        String expected = "{Boats={select=[{boatId={id=1, country=EN}, engine={identification=12345}}]}}";

        //when
        Object result = executor.execute(query).getData();

        // then
        assertThat(result.toString()).isEqualTo(expected);
    }
```

What do you think about it ? It can also cover your complex criteria expressions.

To sum up:

- EmbeddedId and Embedded are both Embeddable and can use the "Reverse Query" syntax with where arg.

- EmbeddedId can be part of the Singular Query syntax, with all values of the key (the AND operator is implicit in this case)

You can see the fix of pr/62/merge in my repo.

Best regards,
ludovicmotte

**Comment by igdianov** [comment]
@ludovicmotte I like your proposal to use reverse query syntax with where in query field for `@EmbeddableId`, but the the explicit AND operator seems to be redundant since AND is always used implicitly by convention. Do you think you can make it implicit by default?

**Comment by ludovicmotte** [comment]
Oups, I closed my pull request without knowing it, but I still want to contribute !
@igdianov My previous test already works if you write with an implicit AND  :

```
String query = "{ Boats { select { boatId(where: {id: { LIKE: \"1\"} country: { EQ: \"EN\"}}) {id country} engine { identification } } } }";
```

Is it what you were exepecting ?

**Comment by ludovicmotte** [comment]
NB : your sample application seems not to work anymore:
```
2019-02-10 18:13:30.229 ERROR 4964 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'graphQLSchemaFactoryBean' defined in class path resource [com/introproventures/graphql/jpa/query/autoconfigure/GraphQLSchemaAutoConfiguration.class]: Invocation of init method failed; nested exception is graphql.AssertException: queryType can't be null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1745) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:827) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at com.introproventures.graphql.jpa.query.example.Application.main(Application.java:33) [classes/:na]
Caused by: graphql.AssertException: queryType can't be null
	at graphql.Assert.assertNotNull(Assert.java:13) ~[graphql-java-11.0.jar:na]
	at graphql.schema.GraphQLSchema.<init>(GraphQLSchema.java:62) ~[graphql-java-11.0.jar:na]
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:340) ~[graphql-java-11.0.jar:na]
	at com.introproventures.graphql.jpa.query.autoconfigure.GraphQLSchemaFactoryBean.createInstance(GraphQLSchemaFactoryBean.java:57) ~[classes/:na]
	at com.introproventures.graphql.jpa.query.autoconfigure.GraphQLSchemaFactoryBean.createInstance(GraphQLSchemaFactoryBean.java:13) ~[classes/:na]
	at org.springframework.beans.factory.config.AbstractFactoryBean.afterPropertiesSet(AbstractFactoryBean.java:142) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	... 16 common frames omitted

```

**Pull request closed without merging**
