### PR TITLE
Support MappedSuperclass

### PR DESCRIPTION
**Pull request by miklemv**
Fix used MappedSuperclass for entity class.

### CODE REVIEW

**Comment by igdianov** [comment]
@miklemv This looks good! Could you, please, add the description that explains the use case, i.e. given->when->then. Thank you very much!

**Comment by igdianov** [comment]
@miklemv Are you around to adjust the PR description and get it merged in the next release?

**Comment by miklemv** [comment]
@igdianov 
Yes. In which files should I make a description? README.md or other?

**Comment by igdianov** [comment]
@miklemv I mean just update the description of the PR.

**Comment by miklemv** [comment]
https://github.com/introproventures/graphql-jpa-query/pull/113

**Pull request closed without merging**
