### PR TITLE
fix: Apply left outer join to retrieve optional associations [WIP]

### PR DESCRIPTION
**Pull request by igdianov**
This PR fixes https://github.com/introproventures/graphql-jpa-query/issues/101

Given optional to-one association, i.e. `favoriteDroid`:

```java
@Entity(name = "Human")
@Data
@EqualsAndHashCode(callSuper=true)
public class Human extends Character {

    String homePlanet;

    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "favorite_droid_id")
    Droid favoriteDroid;

}
```

The GraphQL schema will generate `optional` argument with default value derived from JPA's optional attribute value definition.

```
Type Humans {
   ...
   favoriteDroid(where: DroidsCriteriaExpression, optional: Boolean = true): Droid
   ...
}

```

The JPQL query will now apply left outer join to all queries against entity graph with optional associations, i.e.  given the following query 

```
    Humans {
        select {
            id
            name
            homePlanet
            favoriteDroid {
              name
            }
        }
    }

```

And return all records with optional `favoriteDroid` association null value 

```
{
  "data": {
    "Humans": {
      "select": [
        {
          "id": "1000",
          "name": "Luke Skywalker",
          "homePlanet": "Tatooine",
          "favoriteDroid": {
            "name": "C-3PO"
          }
        },
        {
          "id": "1001",
          "name": "Darth Vader",
          "homePlanet": "Tatooine",
          "favoriteDroid": {
            "name": "R2-D2"
          }
        },
        {
          "id": "1002",
          "name": "Han Solo",
          "homePlanet": null,
          "favoriteDroid": null
        },
        {
          "id": "1003",
          "name": "Leia Organa",
          "homePlanet": "Alderaan",
          "favoriteDroid": null
        },
        {
          "id": "1004",
          "name": "Wilhuff Tarkin",
          "homePlanet": null,
          "favoriteDroid": null
        }
      ]
    }
  }
}
```

It will possible to override `optional` strategy with explicit value, i.e.

```
query {
  Humans {
    select {
      id
      name
      homePlanet
      favoriteDroid(optional: false) {
        name
      }
    }
  }
}
```

Will return the following result:

```
{
  "data": {
    "Humans": {
      "select": [
        {
          "id": "1000",
          "name": "Luke Skywalker",
          "homePlanet": "Tatooine",
          "favoriteDroid": {
            "name": "C-3PO"
          }
        },
        {
          "id": "1001",
          "name": "Darth Vader",
          "homePlanet": "Tatooine",
          "favoriteDroid": {
            "name": "R2-D2"
          }
        }
      ]
    }
  }
}
```

### CODE REVIEW

**Comment by molexx** [comment]
Thanks for this! We've been running against this branch for a few days, the fix works as expected and we haven't noticed any unexpected side effects.

**Comment by igdianov** [comment]
@molexx Thank you for checking. I will refactor and apply optional association fetching after merging PR to support nested associations in where criteria expressions.

**Comment by molexx** [comment]
Thanks! :-)

**Comment by molexx** [comment]
I don't think this is working properly in the merge to master. I've had difficulty proving when it broke because the branch this was on is now deleted and I've not had much success trying to pull builds for commits noted above from jitpack.

I'll continue to investigate tomorrow...

**Comment by molexx** [comment]
Our project works in the old build from that branch but does not work with 0.3.25, yet doing a similar query with the starwars schema using the example project works fine with master.

@igdianov are there any changes to this outer join functionality between the branch and master? Did you implement the `optional` keyword you mentioned? I can't see any changes to the example project or starwars schema to support this? Thanks!

**Comment by igdianov** [comment]
@molexx I had restored `igdianov-use-left-outer-join-original` branch so you could try to use it again and compare generated queries between it and commits in `igdianov-use-left-outer-join`.

I have made the changes only to apply left outer join only for `@ManyToOne` and `@OneToOne` singular attributes. I did not make any changes to schema because the optional attribute is true by default.

**Comment by igdianov** [comment]
@molexx Let me know what you find. Thank you

**Comment by molexx** [comment]
@igdianov thanks for restoring the branches!

`c7754eb` works OK whereas `a6761b46` does not. The JPQL is as expected - when it works there's a `left outer join` between the tables whereas when it doesn't there's an `inner join`.

The parent entity contains a `HashSet` of the child records with `@OneToMany(fetch = FetchType.LAZY, mappedBy=<id of parent in child>)`.

**Comment by igdianov** [comment]
@molexx I need to understand the full context of query to be able to find the solution. The changes that work for you use outer join for all associations, but it is not a good practice for performance reasons. Let me know more details...

**Comment by igdianov** [comment]
@molexx See https://github.com/introproventures/graphql-jpa-query/pull/138 that adds supports for optional join fetch argument for collection attributes

**Pull request merged**
