### PR TITLE
feat: add support for per request schema transformation and instrumentation

### PR DESCRIPTION
**Pull request by igdianov**
This PR adds support for per request schema transformation and instrumentation the uses `GraphQLExecutorContextFactory` interface:

```java
public interface GraphQLExecutorContextFactory {

    GraphQLExecutorContext newExecutorContext(GraphQLSchema graphQLSchema);

}
```

in order to create instance of `GraphQLExecutorContext` interface implemenation that will apply customizations to GraphQL schema field visibility, execution context, and instrumentation before executing query via: 

```java
public interface GraphQLExecutorContext {
    
    ExecutionInput.Builder newExecutionInput();

    GraphQL.Builder newGraphQL();

    GraphQLSchema getGraphQLSchema();
    
}
```

And then in QraphQLExecutor.execute(..)

```java
    /* (non-Javadoc)
     * @see org.activiti.services.query.qraphql.jpa.QraphQLExecutor#execute(java.lang.String, java.util.Map)
     */
    @Override
    @Transactional(TxType.REQUIRED)
    public ExecutionResult execute(String query, Map<String, Object> arguments) {
        Map<String, Object> variables = Optional.ofNullable(arguments)
                                                .orElseGet(Collections::emptyMap);
        
        GraphQLExecutorContext executorContext = contextFactory.newExecutorContext(graphQLSchema);

        ExecutionInput.Builder executionInput = executorContext.newExecutionInput()
                                                               .query(query)
                                                               .variables(variables);        

        GraphQL.Builder graphQL = executorContext.newGraphQL();
        
        return graphQL.build()
                      .execute(executionInput);
    }
```

There is  Spring Boot auto-configuration support for `GraphQLContext`, `GraphqlFieldVisibility` and `Instrumentation` via Java's `Supplier` functional interface, to make it possible use `@RequestScope` magic to inject Supplier functions per request, session, application, i.e.

```java
@Bean
@RequestScope
public Supplier<GraphQLContext> graphqlContext(HttpServletRequest request, @AuthenticationPrincipal UserDetails user) {
    return () -> GraphQLContext.newContext()
                               .of("request", request)
                               .of("user", user)
                               .build();
}
```

TODOs

- [ ] Add test coverage
- [ ] Add documentation in PR with example

Fixes https://github.com/introproventures/graphql-jpa-query/issues/160
Fixes https://github.com/introproventures/graphql-jpa-query/issues/89
Fixes https://github.com/introproventures/graphql-jpa-query/issues/197

### CODE REVIEW

**Comment by igdianov** [comment]
@molexx This is the PR to provide per request schema transformation to be able to apply field visibility function based on user profile in the execution context injection for query security. I will try implement security example using schema directives. Let me know what you think.

**Comment by molexx** [comment]
Thanks @igdianov , sorry I haven't had time to play with this until this week.

Are your comments in the first post still valid after your later changes?
I've built with this branch, I'm calling `schemaBuilder.fieldVisibility()` with my own `GraphqlFieldVisibility` subclass but the methods in it are not called when loading the schema in graphiql.

graphql-java doesn't mention GraphqlFieldVisibility until v12 - although the class is in v11 maybe it isn't used until v12?

If you think it should work then maybe my `fieldVisibility` is not being kept as part of the schema merge in `GraphQLSchemaFactoryBean`? If you think that might be the case I'll investigate, otherwise I might have to wait for the update to graphql-java 13.

**Comment by igdianov** [comment]
@molexx Thanks for feedback. I have not tried this yet and I don't know if `graphqlFieldVisibility` applies to graphq-java 11 or not. I will build a test case to see what is going on...

**Comment by molexx** [comment]
What do you think about this branch @igdianov? I like it because it provides a way to set the GraphQLFieldVisibility which I need to get working at some point, and we need it to set runtime context/environment properties that can be used by RowFilters.

Also it fixes #75.

**Comment by igdianov** [comment]
@molexx I had a break to work on last couple of days. I have refactored the implementation to apply Spring Boot auto-configuration support for GraphQLContext, FieldVisibility and Instrumentation via Java Suppliers, so it will be possible use `@RequestScope` magic to inject functions per request, i.e.

```
    @Bean
    @RequestScope
    public Supplier<GraphQLContext> graphqlContext(HttpServletRequest request, @AuthenticationPrincipal UserDetails user) {
        return () -> GraphQLContext.newContext()
                                   .of("request", request)
                                   .of("user", user)
                                   .build();
    }
```

**Comment by molexx** [comment]
Ah looks great, thanks! I'll try it out.

**Comment by duiscairt-foobar** [comment]
> This PR adds support for per request schema transformation and instrumentation the uses `GraphQLExecutorContextFactory` interface:
> 
> ```java
> public interface GraphQLExecutorContextFactory {
> 
>     GraphQLExecutorContext newExecutorContext(GraphQLSchema graphQLSchema);
> 
> }
> ```
> 
> in order to create instance of `GraphQLExecutorContext` interface implemenation that will apply customizations to GraphQL schema field visibility, execution context, and instrumentation before executing query via:
> 
> ```java
> public interface GraphQLExecutorContext {
>     
>     ExecutionInput.Builder newExecutionInput();
> 
>     GraphQL.Builder newGraphQL();
> 
>     GraphQLSchema getGraphQLSchema();
>     
> }
> ```
> 
> And then in QraphQLExecutor.execute(..)
> 
> ```java
>     /* (non-Javadoc)
>      * @see org.activiti.services.query.qraphql.jpa.QraphQLExecutor#execute(java.lang.String, java.util.Map)
>      */
>     @Override
>     @Transactional(TxType.REQUIRED)
>     public ExecutionResult execute(String query, Map<String, Object> arguments) {
>         Map<String, Object> variables = Optional.ofNullable(arguments)
>                                                 .orElseGet(Collections::emptyMap);
>         
>         GraphQLExecutorContext executorContext = contextFactory.newExecutorContext(graphQLSchema);
> 
>         ExecutionInput.Builder executionInput = executorContext.newExecutionInput()
>                                                                .query(query)
>                                                                .variables(variables);        
> 
>         GraphQL.Builder graphQL = executorContext.newGraphQL();
>         
>         return graphQL.build()
>                       .execute(executionInput);
>     }
> ```
> 
> There is Spring Boot auto-configuration support for `GraphQLContext`, `GraphqlFieldVisibility` and `Instrumentation` via Java's `Supplier` functional interface, to make it possible use `@RequestScope` magic to inject Supplier functions per request, session, application, i.e.
> 
> ```java
> @Bean
> @RequestScope
> public Supplier<GraphQLContext> graphqlContext(HttpServletRequest request, @AuthenticationPrincipal UserDetails user) {
>     return () -> GraphQLContext.newContext()
>                                .of("request", request)
>                                .of("user", user)
>                                .build();
> }
> ```
> 
> TODOs
> 
> * [ ]  Add test coverage
> * [ ]  Add documentation in PR with example
> 
> Fixes #160
> Fixes #89
> Fixes #197

Hi, any plans to merge this?  We use this on a branch and it works well.  It would be great if we could go back to master!
Thanks

**Comment by igdianov** [comment]
@duiscairt-foobar @molexx  It is merged. Feel free to open a PR if need to fix something. :)

**Comment by molexx** [comment]
Ah great thanks!

**Comment by duiscairt-foobar** [comment]
Thanks 😀

**Pull request merged**
